// change this if you want to change the default list of topics
var topics = {
	'Feeling lucky?'   : [
		"How I learnt to be assertive",	
        	"Paying the piper",	
        	"Richard Nixon (US president)",
        	"First manmade island in the US",
        	"Ghosts are real!",
       		"Dictatorships",	
        	"Atomic bombs",	
        	"Quadruplets (four siblings born together)",
        	"My mother in law",
        	"The best holiday destination",
        	"How long are giraffes in labor",
        	"Why homework is bad",
        	"Strategies for potty training",
        	"How to negotiate a raise",
        	"When is it time to get a new job?",
        	"Microbrews vs. standard brewing",
        	"Why pineapple belongs on a pizza",
        	"Benefits of drinking black coffee",
        	"Things you didn’t learn in history class",
        	"How worried should you be about your browsing history?",
        	"Is Bigfoot real?",
        	"When to call 111...",
        	"How to fry an egg",
	],
	'Society': [
		"Baby Boomers vs Millenials",
		"Cat People",
		"Don't try this at home",
		"Door to door sales",
		"Growth Mindset",
		"Happy Marriages",
		"Heavy Metal",
		"If you were born 100 years ago",
		"Living the 'Dream'",
		"Presentation Karaoke",
		"Road Trip",
		"Spending time with your family",
		"Star Trek",
		"Star Wars",
		"Strategy",
		"New Technology",
		"The calm before the storm",
		"The last book you read",
		"This presentation",
		"Traffic in this city",
		"Your boss",
		"Your company",
		"Your dream job",
		"Your favorite pet",
		"Your favourite movie",
		"Your last holiday",
		"Your weekend",
		"Zeppelins and Airships",
    		"Stories From The Past",
    		"Coffee",
	]
};
